### PR TITLE
Add support for Visual Studio 2015+

### PR DESCRIPTION
**Pull request by ladnir**
In this pull require I propose adding support for the Visual Studio compiler. In total, the changes can be summarized as:

- Replace the use of "variable-length automatic array" with malloc(...)/free(...). This is required because VS only supports C90 and Variable-length automatic arrays were added in C99. 
- Setting the WORD size to be 32 bits as opposed to 64 to ensure that the gcc extension uint128_t type is note used. This change has been made to the cmake files when cmake is targeting visual studio. 
- Using WCGR instead of UDEV as the source of random numbers when cmake detects that visual studio is being targeted.
- Added the EXPAND(...) macro to help Visual Studio expand \_\_VA_ARGS\_\_. This is a known bug/workaround in visual studio.
- Small fix with windows header and the pre-processor definition of FIXED. See src/rand/relic_rand_core.c
- Add visual studio (Intel) equivalent of __builtin_clz(...).

This change has been tested both on x64 windows 10 and x64 Linux (CentOS).  If addition changes are required, I would be happy to assist.

Thanks,
Peter Rindal

### CODE REVIEW

**Comment by dfaranha** [comment]
Hi Peter,

My vacations will formally start next week, when I will take care of all the pending stuff with RELIC.

I am happy to merge most of the changes, but switching to malloc/free for everything is tricky, since we decided to move the library to stack-only allocation in the next refactoring.

Hope it helps,

**Comment by ladnir** [comment]
That's no problem, would you be OK with wrapping them in a macro and then it can simply bet set at compile time. I can update this. 

Thanks! 
Peter.

**Comment by conradoplg** [comment]
I once compiled RELIC with Visual Studio and found it easier to compile it as C++, where it has support for variable length arrays, etc.

**Comment by ladnir** [comment]
I do not think that is true.

**Comment by dfaranha** [comment]
Does Visual Studio support alloca.h?

**Comment by ladnir** [comment]
It appears to have _alloca.h. Is the macro option not desirable?

**Comment by dfaranha** [comment]
Using malloc() complicates things due to error-handling. I think it's better if we can enforce stack allocation across all configurations, and alloca() may provide this.

**Comment by ladnir** [comment]
Yeah alloca() sounds reasonable then. Just wrap the header in an if defined to get the right header. alloca.h vs _alloca.h

**Comment by ladnir** [comment]
Closing this one because I have a new pull request with the newest version of relic and using alloca()

**Pull request closed without merging**
