### PR TITLE
Some parameters should be const

### PR DESCRIPTION
**Pull request by jgdumas**
modulus (second argument) should be const in rand_mod?
It is even copied to t ..?

### CODE REVIEW

**Comment by dfaranha** [comment]
BTW, thanks for spotting all these places needing const-correctness annotations!

I procrastinated doing this over EPX for far too long, because I was considering moving from structs to arrays (like FPX), but that should have been settled now.

**Comment by jgdumas** [comment]
Well, yeah it seems in fact hat there are quite a bunch of them!
I undergo doing some, but not sure I'll do them all ;-)

**Comment by dfaranha** [comment]
I would not go as far as FPX yet, because the type changes depending on the memory allocator settings and it might get weird!

**Comment by dfaranha** [comment]
This should be fairly inoffensive and ready to merge. I will do it next weekend, and take the opportunity to complete coverage of const-correctness in the whole library!

**Pull request merged**
