### PR TITLE
Another Visual Studio Port

### PR DESCRIPTION
**Pull request by ladnir**
Hello, I'm here to bother you some more ;)  This is mostly the same as the previous PR #45 with regards to VS 2015.

In total, the changes can be summarized as:

- Replace the use of "variable-length automatic array" with ~~`malloc(...)`/`free(...)`~~ **`alloca(...)` which allocates on the stack without the need to call free**. This is required because VS only supports C90 and Variable-length automatic arrays were added in C99.
- Setting the WORD size to be 32 bits as opposed to 64 to ensure that the gcc extension uint128_t type is not used. This change has been made to the cmake files when cmake is targeting visual studio.
- Default to `WCGR` instead of `UDEV` as the source of random numbers when cmake detects that visual studio is being targeted.
- Added the `EXPAND(...)` macro to help Visual Studio expand `__VA_ARGS__`. This is a known bug/workaround in visual studio.
- Add visual studio (Intel) equivalent of `__builtin_clz(...)`.

There was one change I wanted to point out. https://github.com/ladnir/relic/blob/new_master/src/low/easy/relic_fb_mul_low.c#L153

This line was previously using the `relic_align` macro to align the 2D array. I removed this specifier and added a loop to populate the 2D array. I believe that `alloca(...)` should return aligned memory so this might not be an issue. This seems true on windows at least, see https://msdn.microsoft.com/en-us/library/wb1s57t5.aspx?f=255&MSPPError=-2147217396.

These changes have been tested both on x64 windows 10 and x64 Linux (CentOS). If addition changes are required, I would be happy to assist.

Thanks,
Peter Rindal

### CODE REVIEW

**Comment by ladnir** [comment]
Pinging this. Seems like a good addition :)

**Comment by dfaranha** [comment]
Thank you! It certainly is, I'm only deciding if I apply it before finishing the refactoring or after (and deal with the conflicts).

**Comment by ladnir** [comment]
I see. Well In that case I'm happy to wait. Mostly just wanted to stay in sync with Master.

Cheers

**Comment by dfaranha** [comment]
Hi Peter, it's a long holiday here in Denmark and I am getting RELIC up to speed again. I did a big refactoring of symbols and configuration tweaks which introduced some conflicts with your pull request.

Can you please fix the conflicts so I can finally merge this? :)

**Comment by ladnir** [comment]
Sure.

**Comment by ladnir** [comment]
works on my Linux GCC and windows VS setups...

**Comment by ladnir** [comment]
Thanks!

**Pull request merged**
