### PR TITLE
Implement optimized SSWU map for ep

### PR DESCRIPTION
**Pull request by kwantam**
This PR implements the optimized SSWU map as described in [[WB19]](https://bls-hash.crypto.fyi).

It makes the following changes:

- adds `EP_ISOMAP` build system flag to enable isogeny map--related functions and params
- adds parameters for BLS12-381 isogeny map, plus functions for parsing iso map params
- adds SSWU implementation
- adds isogeny map implementation

This PR isn't quite complete, because I haven't actually hooked up the above in the `ep_map` function yet. I assume we'll do a couple round-trips, edits, etc., and in the meantime I'll get everything hooked up.

### CODE REVIEW

**Comment by kwantam** [comment]
Still WIP. Need to define some parameters for curves that are currently missing them; I believe that's the cause of all the currently failing tests.

**Comment by kwantam** [comment]
Also, I noticed that in `test_ep`, the check for correct hashing to curve doesn't catch all errors. For example, I can make the mapping function return an invalid point and the test still passes. I'll think some about how to improve this situation.

**Comment by kwantam** [comment]
One other thing we might do is change the way string -> field element hashing is done. The way that the hash-to-curve draft does it is conservatively designed against bad hash functions, etc. Happy to impl this.

**Comment by kwantam** [comment]
Note: rebased on #131.

**Comment by dfaranha** [comment]
Thanks for the wonderful work! Merged for further integration work. :)

**Pull request merged**
