### PR TITLE
Add simultaneous fixed point multiplication support

### PR DESCRIPTION
**Pull request by etairi**
I added some basic functions to support simultaneous point multiplication using precomputation tables. It's purely because I needed something like this, but I believe it can be beneficial to others that need something similar. 

Here are some benchmark results:
```
BENCH: g1_mul_sim                       = 238285 nanosec
BENCH: g1_mul_sim_gen                   = 239291 nanosec
BENCH: g1_mul_sim_fix                   = 172002 nanosec
.
.
.
BENCH: g2_mul_sim                       = 844558 nanosec
BENCH: g2_mul_sim_gen                   = 838559 nanosec
BENCH: g2_mul_sim_fix                   = 589329 nanosec
```

### CODE REVIEW

**Comment by dfaranha** [comment]
Thank you! At first I thought this would allow just one point to be precomputed like mul_sin_gen() but with a non-generator point.

What is the intended application of this? Do you have an example protocol?

**Comment by etairi** [comment]
I pushed another commit with some fixes. I had forgotten to cover the case when a user doesn't provide one or both of the precomputation tables. In that case I made sure that we calculate the precomputation tables inside the function. Of course, this is not very clever and will be slower than any other multiplication alone, but I believe it is better than failing in those cases. So, the scenario where this makes sense to gain speedup is when the user provides both of the precomputation tables.

One possible application of this when used in something like HIBE schemes (let's say form of BBG HIBE). In that case one has to usually calculate a product of the form h_1^I_1 \cdots h_k^I_k, where the h_i's are fixed and I_i's change. So, one can precompute the tables for h_i's, and then apply pairwise simultaneous multiplications. Of course, any other product of similar form would benefit from something like this.

**Comment by dfaranha** [comment]
Calculating the precomputation table is basically never worth it if you are using the function a few times.

**Comment by etairi** [comment]
You are right. Indeed, it doesn't seem to be worth it. I pushed a new commit, where I made sure we switch to standard scalar multiplication if any of the precomputation tables are not provided.

**Pull request closed without merging**
