### PR TITLE
cmake: Always use user defined CFLAGS, not only for release builds

### PR DESCRIPTION
**Pull request by xdustinface**

### CODE REVIEW

**Comment by dfaranha** [comment]
Hi, I've thought about this before. The point is to build with release flags AND debugging symbols?

**Comment by xdustinface** [comment]
Hey,

the reason for this PR is that we need to provide custom flags for includes also in debug build. I guess an other option would be to always pass the existing environment `CFLAGS` through. Maybe something like: 

```
if(DEBUG)
	set(CFLAGS "-O0 -fno-omit-frame-pointer $ENV{CFLAGS}" CACHE STRING)
	set(DFLAGS "-ggdb")
else()
	set(CFLAGS "-O2 -funroll-loops -fomit-frame-pointer $ENV{CFLAGS}" CACHE STRING)
endif()
```

Didn't test this ^ but i guess i should work. But my feeling says just having the option to fully take control of the flags is better? Thoughts?

**Comment by xdustinface** [comment]
@dfaranha any thoughts about the above?

**Comment by dfaranha** [comment]
I think it makes sense and DEBUG might just enable debugging symbols when custom CFLAGs are passed. I will merge and do some minor adjustments tonight, after I give some testing. Last time I played with CFLAGS I broke a few projects depending on RELIC. :)

**Comment by dfaranha** [comment]
Merged with a tiny adjustment! Hope it does not break builds elsewhere :)

**Pull request merged**
