### PR TITLE
Paillier's subgroup variant, as cp_shpe

### PR DESCRIPTION
**Pull request by jgdumas**
With a subgroup of cardinality less than lambda:

- Decryption is faster than Paillier
- Encryption also if the private key is known  (hence useful for instance in multi-party settings).

### CODE REVIEW

**Comment by dfaranha** [comment]
Thank you! Is this particular variant over a subgroup described somewhere?

**Comment by jgdumas** [comment]
Ah yes, this is "Scheme 3" in the original P. Paillier's paper at Eurocrypt'99.
Here this is a CRT version with generator g=(1+n)^b of order 'a' (alpha in the paper) : 'a' is a factor of (p-1), and lambda=a * b.

**Comment by dfaranha** [comment]
I just slightly changed some things (`shpe_t` type, testing code) to better match the current version of the library, hope it's ok! :)

**Comment by jgdumas** [comment]
Hello ok for me, no problem.
(I also thought about factoring the crt part, there are pros and cons: less code but different meaning and slightly more cumbersome access, but again both choices work for me ...).

**Pull request merged**
